language: python
python:
  - "3.7"

# sudo and dist are required so that Python 3.7
# can be used, this is the official way to do it.
# See: github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

env:
  global:
    - DATABASE_URL="postgres://postgres:@127.0.0.1:5432/evonoveit"
  matrix:
    - PSQL_VERSION=9.5.5 REDIS_VERSION=3.2.6

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop
  - docker pull postgres:$PSQL_VERSION
  - docker pull redis:$REDIS_VERSION
  - docker run -d -p 127.0.0.1:5432:5432 postgres:$PSQL_VERSION
  - docker run -d -p 127.0.0.1:6379:6379 redis:$REDIS_VERSION

install:
  - pip install tox

script:
  - tox -r
