sudo: required

language: python
python:
  - "3.5"

env:
  global:
    - DATABASE_URL="postgres://postgres:@127.0.0.1:5432/evonoveit"
  matrix:
    - PSQL_VERSION=9.5.0 REDIS_VERSION=3.0.6

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop
  - docker pull postgres:$PSQL_VERSION
  - docker pull redis:$REDIS_VERSION
  - docker run -d -p 127.0.0.1:5432:5432 postgres:$PSQL_VERSION
  - docker run -d -p 127.0.0.1:6379:6379 redis:$REDIS_VERSION

install:
  - pip install tox

script:
  - tox -r
