include:
  - docker-services.yml

services:
  django:
    build:
      context: .
      dockerfile: containers/Dockerfile
    env_file: ".env.docker"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
