# This file must be used only for development purposes
version: "2"

services:
    postgres:
        image: postgres:9.5.2
        environment:
            - POSTGRES_USER=devel
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=evonoveit

    redis:
        image: redis:3.0.7

    django:
        build: .
        volumes:
          - .:/app
        ports:
          - "8000:8000"
