services:
  postgres:
    image: postgres:13.20
    restart: "on-failure"
    env_file: ".env.docker"
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h $$POSTGRES_HOST -p $$POSTGRES_PORT",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.3
    restart: "on-failure"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"