[tool.poetry]
name = "evonove.it"
version = "3.4.6"
description = ""
authors = ["Evoniners <dev@evonove.it>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "2.2.10"
django-getenv = "1.3.2"
django-redis = "4.10.0"
dj-database-url = "0.5.0"
psycopg2-binary = "2.8.3"
whitenoise = "4.1.3"
wagtail = "2.6.1"
Pygments = "2.4.2"
uWSGI = "2.0.18"
django-s3-storage = "0.12.5"
raven = "6.10.0"
python-json-logger = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "5.1.1"
pytest-cov = "2.7.1"
pytest-django = "3.5.1"
pytest-xdist = "1.29.0"
flake8 = "3.7.8"
coverage = "4.5.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
