[pytest]
testpaths = django-website
addopts =
    -vvv
    --cov django-website
    --cov-report term-missing:skip-covered
    --ignore=django-website/frontend/node_modules/

[tox]
requires =
    tox>=4
envlist = ruff, ruff-format, py313, trivy

[testenv:py313]
runner = uv-venv-lock-runner
skip_install = true
set_env =
    DJANGO_SETTINGS_MODULE=website.settings
passenv = *
commands =
    python django-website/manage.py makemigrations --check --dry-run
    python runtests.py

[testenv:ruff]
description = Run Ruff Linter
skip_install = true
deps =
    ruff
commands = ruff check django-website

[testenv:ruff-format]
description = Run Black Formatter
skip_install = true
deps =
    ruff
commands = ruff format --exclude migrations,node_modules --check django-website

[testenv:trivy]
description = Run trivy scan in local project
skip_install = true
allowlist_externals = sh
commands =
    sh -c 'docker run --rm -v $(pwd):/evonove aquasec/trivy fs \
	    --severity HIGH,CRITICAL \
        --scanners vuln,misconfig,secret /evonove \
        --skip-dirs /evonove/.tox,/evonove/.venv --ignore-unfixed \
        --format table'
