# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='job_email',
            field=models.EmailField(blank=True, help_text='job email address', max_length=255, null=True),
        ),
    ]
