# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 11:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20170727_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='linked_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Linked Data in JSON', null=True),
        ),
    ]
