version: "2"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=devel
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=evonoveit

  redis:
    image: redis:latest

  django:
    build:
      context: ../
      dockerfile: containers/Dockerfile
    ports:
      - "8000:8000"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
