# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:33
from __future__ import unicode_literals

import blog.fields
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=wagtail.fields.StreamField((('h2', wagtail.blocks.CharBlock(icon='title')), ('h3', wagtail.blocks.CharBlock(icon='title')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', blog.fields.ImageFormatBlock()), ('caption', wagtail.blocks.RichTextBlock(required=False))), icon='image', label='Aligned image')), ('youtube', wagtail.blocks.StructBlock((('identifier', wagtail.embeds.blocks.EmbedBlock()),), icon='image')), ('pullquote', wagtail.blocks.StructBlock((('quote', wagtail.blocks.TextBlock(label='Quote title')), ('attribution', wagtail.blocks.CharBlock())), icon='openquote')))),
        ),
    ]
