# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 11:13
from __future__ import unicode_literals

import blog.fields
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160509_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=wagtail.fields.StreamField((('h2', wagtail.blocks.CharBlock(icon='title')), ('h3', wagtail.blocks.CharBlock(icon='title')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', blog.fields.ImageFormatBlock()), ('caption', wagtail.blocks.RichTextBlock(required=False))), icon='image', label='Aligned image')), ('youtube', wagtail.blocks.StructBlock((('identifier', wagtail.embeds.blocks.EmbedBlock()),), icon='image')), ('pullquote', wagtail.blocks.StructBlock((('quote', wagtail.blocks.TextBlock(label='Quote title')), ('attribution', wagtail.blocks.CharBlock())), icon='openquote')), ('code_snippet', wagtail.blocks.StructBlock((('language', wagtail.blocks.ChoiceBlock(choices=[('python', 'Python'), ('cpp', 'C++'), ('html', 'HTML'), ('css', 'CSS')])), ('code_text', wagtail.blocks.TextBlock())), icon='code', label='Code Snippet')))),
        ),
    ]
