# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 10:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170310_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
