# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170803_0905'),
        ('blog', '0004_blogpage_blog_subtitle'),
    ]

    operations = [
    ]
