# Generated by Django 3.2.23 on 2023-11-09 15:22

import blog.fields
from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20170803_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(icon='title')), ('h3', wagtail.blocks.CharBlock(icon='title')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', blog.fields.ImageFormatBlock()), ('caption', wagtail.blocks.RichTextBlock(required=False))], icon='image', label='Aligned image')), ('youtube', wagtail.embeds.blocks.EmbedBlock(icon='image')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(label='Quote title')), ('attribution', wagtail.blocks.CharBlock())], icon='openquote')), ('code_snippet', wagtail.blocks.StructBlock([('language', wagtail.blocks.ChoiceBlock(choices=[('python', 'Python'), ('cpp', 'C++'), ('html', 'HTML'), ('css', 'CSS')])), ('code_text', wagtail.blocks.TextBlock())], icon='code', label='Code Snippet'))], use_json_field=True),
        ),
    ]
