version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0

jobs:
  run-tests:
    docker:
      - image: cimg/python:3.7
      - image: cimg/postgres:9.6
        environment:
          POSTGRES_USER: devel
          POSTGRES_DB: evonoveit
          POSTGRES_PASSWORD: "123456"
      - image: redis:6.2
    steps:
      - checkout
      - run:
          name: "Install poetry"
          command: |
            pip install poetry
      - restore_cache:
          keys:
            - poetry-cache-{{ checksum "poetry.lock" }}
      - run:
          name: "Install dependencies"
          command: |
            poetry install
      - save_cache:
          key: poetry-cache-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
      - run:
          name: "Run tests"
          command: |
            poetry run pytest
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: evonoveit-test-circleci-build
          dockerfile: containers/Dockerfile
          no_output_timeout: 20m
          registry-url: gcr.io
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: evonoveit-test-circleci-build
          registry-url: gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  testing:
    jobs:
      - run-tests
      - build-and-push
