version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0

executors:
  builder-executor:
    docker:
      - image: 'cimg/python3.7'

jobs:
  run-tests:
    docker:
      - image: cimg/python:3.7
      - image: cimg/postgres:9.6
        environment:
          POSTGRES_USER: devel
          POSTGRES_DB: evonoveit
          POSTGRES_PASSWORD: "123456"
      - image: redis:6.2
    steps:
      - checkout
      - run:
          name: "Install poetry"
          command: |
            pip install poetry
      - restore_cache:
          keys:
            - poetry-cache-{{ checksum "poetry.lock" }}
      - run:
          name: "Install dependencies"
          command: |
            poetry install
      - save_cache:
          key: poetry-cache-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
      - run:
          name: "Run tests"
          command: |
            poetry run pytest

workflows:
  testing:
    jobs:
      - run-tests
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          executor: builder-executor
          image: evonoveit-test-circleci-build
          dockerfile: containers/Dockerfile
          registry-url: gcr.io
          setup-remote-docker: true
          use-docker-layer-caching: true
