version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          command: |
            pip install tox
      - run:
          name: Run tests
          command: tox

workflows:
  sample:
    jobs:
      - build-and-test
