version: 2.1

parameters:
  repository-name:
    type: string
    default: "evonove-it"
  image-name:
    type: string
    default: "evonove-it-backend"

orbs:
  python: circleci/python@3.1.0
  gcp-gcr: circleci/gcp-gcr@0.16.10

executors:
  builder:
    docker:
      - image: cimg/python:3.11.6

workflows:
  test_build_push:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build-and-push:
          context:
            - google-cloud-platform
          requires:
            - test
          filters:
            tags:
              only: /.*/

jobs:
  test:
    docker:
      - image: cimg/python:3.11.6
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: cimg/postgres:13.20
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_DB: evonoveit
          POSTGRES_USER: devel
          POSTGRES_PASSWORD: 123456
      - image: cimg/redis:7.2.3
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - run:
          name: Formatter check
          command: uv run ruff format --exclude migrations --check django-website
      - run:
          name: Linter check
          command: uv run ruff check django-website
      - run:
          name: Migrations check
          environment:
            DJANGO_SETTINGS_MODULE: website.settings.test
          command: uv run python django-website/manage.py makemigrations --check --dry-run
      - run:
          name: Run tests
          environment:
            DJANGO_SETTINGS_MODULE: website.settings.test
          command: |
            mkdir test-results
            uv run python runtests.py \
                --cov django-website \
                --cov-report html:htmlcov \
                --junitxml=test-results/junit.xml \
                django-website/
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
  build-and-push:
    executor:
      builder
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - gcp-gcr/gcr-auth:
          gcloud-service-key: CLEARTEXT_GCLOUD_SERVICE_KEY
          registry-url: europe-west3-docker.pkg.dev
      - gcp-gcr/build-image:
          image: << pipeline.parameters.repository-name >>/<< pipeline.parameters.image-name >>
          tag: $CIRCLE_SHA1
          dockerfile: containers/Dockerfile
          registry-url: europe-west3-docker.pkg.dev
      - gcp-gcr/push-image:
          image: << pipeline.parameters.repository-name >>/<< pipeline.parameters.image-name >>
          tag: $CIRCLE_SHA1
          registry-url: europe-west3-docker.pkg.dev
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - gcp-gcr/tag-image:
                registry-url: europe-west3-docker.pkg.dev
                image: << pipeline.parameters.repository-name >>/<< pipeline.parameters.image-name >>
                source-tag: $CIRCLE_SHA1
                target-tag: $CIRCLE_TAG
