version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          args: tox
          pkg-manager: pip
          pypi-cache: false
      - run:
          name: Run tests
          command: tox

workflows:
  sample:
    jobs:
      - build-and-test
