version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
      - image: cimg/postgres:9.6
        environment:
          POSTGRES_USER: devel
          POSTGRES_DB: evonoveit
          POSTGRES_PASSWORD: "123456"
      - image: redis:6.2
    steps:
      - checkout
      - run:
          name: "Install poetry"
          command: |
            pip install poetry
      - restore_cache:
          keys:
            - poetry-cache-{{ checksum "poetry.lock" }}
      - run:
          name: "Install dependencies"
          command: |
            poetry install
      - save_cache:
          key: poetry-cache-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
      - run:
          name: "Run tests"
          command: |
            poetry run pytest

workflows:
  sample:
    jobs:
      - build-and-test
