version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0

jobs:
  run-tests:
    docker:
      - image: cimg/python:3.7
      - image: cimg/postgres:9.6
        environment:
          POSTGRES_USER: devel
          POSTGRES_DB: evonoveit
          POSTGRES_PASSWORD: "123456"
      - image: redis:6.2
    steps:
      - checkout
      - run:
          name: "Install poetry"
          command: |
            pip install poetry
      - restore_cache:
          keys:
            - poetry-cache-{{ checksum "poetry.lock" }}
      - run:
          name: "Install dependencies"
          command: |
            poetry install
      - save_cache:
          key: poetry-cache-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
      - run:
          name: "Run tests"
          command: |
            poetry run pytest
  build-and-push:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GCP_PROJECT_KEY
          google-project-id: GOOGLE_PROJECT_ID
      - gcp-gcr/build-image:
          dockerfile: containers/Dockerfile
          google-project-id: GOOGLE_PROJECT_ID
          image: evonoveit-test-circleci-build
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          image: evonoveit-test-circleci-build

workflows:
  test_and_build:
    jobs:
      - run-tests
      - build-and-push
