# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 08:01
from __future__ import unicode_literals

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_auto_20170727_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
