# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 08:05
from __future__ import unicode_literals

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_auto_20170804_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringpage',
            name='outro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
