# Generated by Django 3.2.23 on 2023-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0006_hiringpage_outro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringpage',
            name='linked_data',
            field=models.JSONField(blank=True, help_text='Linked Data in JSON', null=True),
        ),
    ]
