# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 09:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfoliopage_linked_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=wagtail.fields.RichTextField(),
        ),
    ]
