# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20170726_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencypage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
