# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_auto_20170731_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='deviantart',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='flickr',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='stackoverflow',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='tumblr',
        ),
    ]
