# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_agencypage_linked_data'),
        ('agency', '0007_auto_20170731_1134'),
    ]

    operations = [
    ]
