# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20170801_0717'),
        ('agency', '0008_merge_20170801_1309'),
    ]

    operations = [
    ]
