# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:51
from __future__ import unicode_literals

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_merge_20170801_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypage',
            name='services_contact',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
