# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_agencypage_services_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypage',
            name='stack_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
