# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 09:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_agencypage_stack_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
