# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 08:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160129_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=wagtail.core.fields.RichTextField(help_text='The team member bio', max_length=320),
        ),
    ]
