# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 07:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160511_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='The team member bio', max_length=360),
        ),
    ]
