# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160512_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
