# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_work_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='work',
            name='technologies',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
