# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 11:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_work_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='linked_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Linked Data in JSON', null=True),
        ),
    ]
