# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_linked_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='page',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='work',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='work',
            name='page',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='service',
            name='technologies',
        ),
        migrations.AddField(
            model_name='homepage',
            name='payoff',
            field=wagtail.fields.RichTextField(blank=True, help_text='Home intro'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
