# Generated by Django 3.2.23 on 2023-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170727_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='linked_data',
            field=models.JSONField(blank=True, help_text='Linked Data in JSON', null=True),
        ),
    ]
