# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:53
from __future__ import unicode_literals

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_websitesettings_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='address',
            field=wagtail.fields.RichTextField(help_text='Your company address'),
        ),
    ]
